# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UcBdhruilnvA_osyx4KSNKeDsoDmmL1U
"""

import cv2 as cv
import numpy as np

pip install wget

import wget
import os
from google.colab.patches import cv2_imshow
url = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimg.freepik.com%2Fpremium-photo%2Fhand-reaching-up-sun-with-sun-shining-through-fingers_593294-11055.jpg&f=1&nofb=1&ipt=1e524bbe102cde52453fc3407e94b12d836dcd2aa9c2ea175965c65a24b7ddc5"
filename = wget.download(url)
print(os.path.abspath(filename))

colors = cv.imread(filename)
colors = cv.cvtColor(colors, cv.COLOR_BGR2RGB)

img_ycrcb = cv.cvtColor(colors, cv.COLOR_BGR2YCrCb)
Y, Cr, Cb = cv.split(img_ycrcb)
avg_lum = np.mean(Y)

clache = cv.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
Y_clahe = clache.apply(Y)
img2 = cv.merge((Y_clahe, Cr, Cb))
img2 = cv.cvtColor(img2, cv.COLOR_YCrCb2BGR)

#cv2_imshow(img2)
edges = cv.Canny(img2, 100, 200)
cv2_imshow(edges)

#sobel: (l) luminance, pocitame s respektem k ose (x,y)
sobel_x = cv.Sobel(edges, cv.CV_64F, 1,0,ksize=3)
sobel_y = cv.Sobel(edges, cv.CV_64F, 0,1,ksize=3)
sobelx8 = cv.convertScaleAbs(sobel_x)
sobely8 = cv.convertScaleAbs(sobel_y)
mag = cv.convertScaleAbs(cv.magnitude(sobel_x, sobel_y))
sobel_rgb = cv.merge((sobelx8, sobely8, mag))
#cv2_imshow(sobel_rgb)

#laplacian obrazku (druha derivace s respektem k (x,y))
laplacian_img=cv.Laplacian(sobel_rgb, cv.CV_64F)

ycrcb = cv.cvtColor(img2, cv.COLOR_BGR2YCrCb)
y, _, _ = cv.split(ycrcb)
cv2_imshow(y)

converted_laplacian = cv.convertScaleAbs(laplacian_img)
laplacian_gray = cv.cvtColor(converted_laplacian, cv.COLOR_BGR2GRAY)

cv2_imshow(laplacian_gray)

from scipy import ndimage

_, maska = cv.threshold(laplacian_gray, 1, 240, cv.THRESH_BINARY)
mask = maska.astype(np.bool)

labeled_mask, num_labels = ndimage.label(mask)
#cv2_imshow(labeled_mask)
print(num_labels)

cluster = []
for i in range(1, num_labels + 1):
  label_mask = (labeled_mask == i)
  cluster.append(label_mask)

import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(10,10))
plt.imshow(labeled_mask, cmap='nipy_spectral')
plt.colorbar(label="Cluster ID")
plt.title("Vizualizace clusterů")

for i, label_mask in enumerate(cluster, start=1):
    coords = np.argwhere(label_mask)
    y, x = coords.mean(axis=0)
    plt.text(x, y, str(i), color='white', fontsize=12, ha='center', va='center')

plt.show()

img2_gray = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)

keys = np.array(cluster)
keys.shape, img2.shape

sliced = []
sliced_gray = []
for i,coords in enumerate(keys):
  #print(i, coords)
  sliced.append(img2[coords])
  sliced_gray.append(img2_gray[coords])

np.array(sliced, dtype=object).shape
np.array(sliced_gray, dtype=object).shape

for i in range(len(sliced)):
  print(sliced[i].shape)
  print(f"Cluster {i}: len={len(sliced[i].shape)}, min={sliced[i].min()}, max={sliced[i].max()}, mean={sliced[i].mean():.2f}, std={sliced[i].std():.2f}")

kernel_size = 15
kernel = np.ones((kernel_size, kernel_size), np.float32) / (kernel_size * kernel_size)
local_mean = cv.filter2D(img2_gray, -1, kernel)

print(local_mean.shape)
cluster_means = []

for i in range(len(sliced_gray)):
  cluster_means.append(img2_gray[sliced_gray[i]].mean())

diff = [local_mean - cluster_means[i] for i in range(len(sliced_gray))]
diff_with_index = [(local_mean - cluster_means[i], i) for i in range(len(sliced_gray))]

diff = np.array(diff, dtype=object)

plate = np.zeros_like(img2_gray, dtype=np.float32)

for i, cluster_mask in enumerate(sliced_gray):
    plate[cluster_mask] = diff[i][cluster_mask]

plt.figure(figsize=(10,10))
plt.imshow(labeled_mask, cmap='nipy_spectral')

for i, label_mask in enumerate(cluster, start=1):
    coords = np.argwhere(label_mask)
    y, x = coords.mean(axis=0)
    plt.text(x, y, str(i), color='white', fontsize=12, ha='center', va='center')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(10,10))

plt.imshow(labeled_mask, cmap='nipy_spectral', alpha=0.6)

plt.imshow(plate, cmap='bwr', alpha=0.4)

for i, label_mask in enumerate(cluster, start=1):
    coords = np.argwhere(label_mask)
    y, x = coords.mean(axis=0)
    plt.text(x, y, str(i), color='white', fontsize=12, ha='center', va='center')

plt.title("Clusters with plate overlay")
plt.axis('off')
plt.colorbar(label="Contrast / local difference")
plt.show()

